services:
  mariadb:
    image: mariadb:10.11
    container_name: infra-mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "6001:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - phantasm-net

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: infra-pma
    restart: always
    environment:
      PMA_HOST: mariadb
      UPLOAD_LIMIT: 64M
    ports:
      - "7001:80"
    networks:
      - phantasm-net

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: infra-mqtt
    restart: always
    profiles:
      - mqtt
    ports:
      - "6002:1883"
      - "6003:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - phantasm-net

  mqtt-explorer:
    image: smeagolworms4/mqtt-explorer
    container_name: infra-mqtt-web
    restart: always
    profiles:
      - mqtt
    ports:
      - "7002:4000"
    environment:
      - HTTP_PORT=4000
    depends_on:
      - mosquitto
    networks:
      - phantasm-net

  postgres:
    image: postgres:15-alpine
    container_name: infra-postgres
    restart: always
    profiles:
      - postgres
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - "6004:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - phantasm-net

  redis:
    image: redis:7-alpine
    container_name: infra-redis
    restart: always
    profiles:
      - redis
    ports:
      - "6005:6379"
    volumes:
      - redis_data:/data
    networks:
      - phantasm-net

networks:
  phantasm-net:
    name: phantasm-net
    driver: bridge

volumes:
  mysql_data:
  postgres_data:
  redis_data:
