services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_UID: ${UID:-1000}
        APP_GID: ${GID:-1000}
    user: "${UID:-1000}:${GID:-1000}"
    container_name: boilerplate-app-dev
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
    networks:
      - mirage-net

  nginx:
    image: nginx:alpine
    container_name: boilerplate-nginx-dev
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - mirage-net

networks:
  mirage-net:
    external: true
    name: mirage-net
